version: '3.9'

services:
  django:
    build:
      context: ./django
    container_name: django_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django:/app
    env_file:
      - .env
    expose:
      - '8000'
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:14
    container_name: postgres_db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    expose:
      - '5432'
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - django
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
